//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen --output=Models --namespace=AssinadorNFTS.Models nfts\RetornoEnvioNFTS_v01.xsd
namespace AssinadorNFTS.Models
{
    
    
    /// <summary>
    /// <para>Tipo referente aos possíveis tipos da NFTS.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Tipo referente aos possíveis tipos da NFTS.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpTipoDocumentoNFTS", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    public enum TpTipoDocumentoNfts
    {
        
        /// <summary>
        /// <para>Dispensado de emissão de documento fiscal.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Dispensado de emissão de documento fiscal.")]
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        /// <summary>
        /// <para>Com emissão de documento fiscal autorizado pelo município.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Com emissão de documento fiscal autorizado pelo município.")]
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        /// <summary>
        /// <para>Sem emissão de documento fiscal embora obrigado.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Sem emissão de documento fiscal embora obrigado.")]
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
    }
    
    /// <summary>
    /// <para>Tipo referente aos possíveis status de NFTS.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Tipo referente aos possíveis status de NFTS.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpStatusNFTS", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    public enum TpStatusNfts
    {
        
        /// <summary>
        /// <para>Normal.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Normal.")]
        N,
        
        /// <summary>
        /// <para>Cancelada.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Cancelada.")]
        C,
    }
    
    /// <summary>
    /// <para>Tipo referente aos modos de tributação da NFTS.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Tipo referente aos modos de tributação da NFTS.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpTributacaoNFTS", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    public enum TpTributacaoNfts
    {
        
        /// <summary>
        /// <para>Operação Normal.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Operação Normal.")]
        T,
        
        /// <summary>
        /// <para>Imune.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Imune.")]
        I,
        
        /// <summary>
        /// <para>ISS Suspenso por Decisão Judicial.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ISS Suspenso por Decisão Judicial.")]
        J,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpEvento", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpEvento
    {
        
        /// <summary>
        /// <para>Código do evento.</para>
        /// <para>Tipo código de evento.</para>
        /// <para xml:lang="en">Pattern: [0-9]{3,4}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código do evento.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{3,4}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Codigo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Codigo { get; set; }
        
        /// <summary>
        /// <para>Descrição do enveto.</para>
        /// <para>Tipo descrição do evento.</para>
        /// <para xml:lang="en">Maximum length: 300.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição do enveto.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(300)]
        [System.Xml.Serialization.XmlElementAttribute("Descricao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Descricao { get; set; }
        
        /// <summary>
        /// <para>Informações que irão identificar o documento onde ocorreu o problema.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informações que irão identificar o documento onde ocorreu o problema.")]
        [System.Xml.Serialization.XmlElementAttribute("IdentificacaoDocumento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpIdentificacaoDocumento IdentificacaoDocumento { get; set; }
        
        /// <summary>
        /// <para>Informações que irão identificar a NFTS onde ocorreu o problema.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informações que irão identificar a NFTS onde ocorreu o problema.")]
        [System.Xml.Serialization.XmlElementAttribute("IdentificacaoNFTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpIdentificacaoNfts IdentificacaoNfts { get; set; }
    }
    
    /// <summary>
    /// <para>Identificação da NFTS.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Identificação da NFTS.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpIdentificacaoDocumento", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpIdentificacaoDocumento
    {
        
        /// <summary>
        /// <para>Indica a posição da NFTS no arquivo XML.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,2}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Indica a posição da NFTS no arquivo XML.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,2}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Posicao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Posicao { get; set; }
        
        /// <summary>
        /// <para>Informe a chave do documento Inscrição Municipal/Sério/Número documento da NFTS.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe a chave do documento Inscrição Municipal/Sério/Número documento da NFTS.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ChaveDocumento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpChaveDocumento ChaveDocumento { get; set; }
    }
    
    /// <summary>
    /// <para>Chave de identificação da NFTS.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Chave de identificação da NFTS.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpChaveDocumento", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpChaveDocumento
    {
        
        /// <summary>
        /// <para>Informe a Inscrição Municipal da NFTS.</para>
        /// <para>Tipo padrão referente a inscrição municipal.</para>
        /// <para xml:lang="en">Pattern: [0-9]{8,8}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe a Inscrição Municipal da NFTS.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{8,8}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("InscricaoMunicipal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long InscricaoMunicipal { get; set; }
        
        /// <summary>
        /// <para>Informe a série da NFTS.</para>
        /// <para>Tipo série de documento NFTS.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 5.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe a série da NFTS.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(5)]
        [System.Xml.Serialization.XmlElementAttribute("SerieNFTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerieNfts { get; set; }
        
        /// <summary>
        /// <para>Informe o número do documento.</para>
        /// <para>Informe o número do documento da NTFS.</para>
        /// <para xml:lang="en">Total number of digits: 12.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o número do documento.")]
        [System.Xml.Serialization.XmlElementAttribute("NumeroDocumento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ulong NumeroDocumento { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the NumeroDocumento property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumeroDocumentoSpecified { get; set; }
    }
    
    /// <summary>
    /// <para>Identificação da NFTS.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Identificação da NFTS.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpIdentificacaoNFTS", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpIdentificacaoNfts
    {
        
        /// <summary>
        /// <para>Indica a posição da NFTS no arquivo XML.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,2}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Indica a posição da NFTS no arquivo XML.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,2}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Posicao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Posicao { get; set; }
        
        /// <summary>
        /// <para>Informe a chave do documento Inscrição Municipal/Número NFTS/Código de Verificação da NFTS.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Informe a chave do documento Inscrição Municipal/Número NFTS/Código de Verificaçã" +
            "o da NFTS."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ChaveNFTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpChaveNfts ChaveNfts { get; set; }
    }
    
    /// <summary>
    /// <para>Chave de identificação da NFTS.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Chave de identificação da NFTS.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpChaveNFTS", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpChaveNfts
    {
        
        /// <summary>
        /// <para>Informe a Inscrição Municipal da NFTS.</para>
        /// <para>Tipo padrão referente a inscrição municipal.</para>
        /// <para xml:lang="en">Pattern: [0-9]{8,8}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe a Inscrição Municipal da NFTS.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{8,8}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("InscricaoMunicipal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long InscricaoMunicipal { get; set; }
        
        /// <summary>
        /// <para>Número da NFS-e.</para>
        /// <para>Informe o número da NTFS.</para>
        /// <para xml:lang="en">Total number of digits: 12.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número da NFS-e.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("NumeroNFTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ulong NumeroNfts { get; set; }
        
        /// <summary>
        /// <para>Código de verificação da NFTS.</para>
        /// <para>Tipo Código de verificação da NFTS.</para>
        /// <para xml:lang="en">Minimum length: 8.</para>
        /// <para xml:lang="en">Maximum length: 8.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código de verificação da NFTS.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(8)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(8)]
        [System.Xml.Serialization.XmlElementAttribute("CodigoVerificacao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoVerificacao { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpInformacoesLoteNFTS", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpInformacoesLoteNfts
    {
        
        /// <summary>
        /// <para>Número do lote gerado pelo processamento.</para>
        /// <para>Indica o número do lote gerado pelo processamento.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número do lote gerado pelo processamento.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("NumeroLote", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ulong NumeroLote { get; set; }
        
        /// <summary>
        /// <para>Dados do Remetente do Lote da mensagem XML transmitida.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Dados do Remetente do Lote da mensagem XML transmitida.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Remetente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpRemetente Remetente { get; set; }
        
        /// <summary>
        /// <para>Retorna a data de envio do lote (AAAA-MM-DDTHH:mm:ss).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Retorna a data de envio do lote (AAAA-MM-DDTHH:mm:ss).")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dtEnvioLote", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime DtEnvioLote { get; set; }
        
        /// <summary>
        /// <para>Retorna a quantidade de NFTS processadas.</para>
        /// <para>Tipo padrão para quantidades.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,15}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Retorna a quantidade de NFTS processadas.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,15}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("QtdeNFTSProcessadas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long QtdeNftsProcessadas { get; set; }
        
        /// <summary>
        /// <para>Retorna o tempo de processamento do lote.</para>
        /// <para>Tipo referente ao tempo de processamento do lote.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,15}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Retorna o tempo de processamento do lote.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,15}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("TempoProcessamento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long TempoProcessamento { get; set; }
        
        /// <summary>
        /// <para>Retorna o valor total dos serviços das NFTS contidos na mensagem XML.</para>
        /// <para>Tipo utilizado para valores com 15 dígitos, sendo 13 de corpo e 2 decimais.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{0,2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Retorna o valor total dos serviços das NFTS contidos na mensagem XML.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{0,2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ValorTotalServicos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValorTotalServicos { get; set; }
    }
    
    /// <summary>
    /// <para>Dados do Remetende CPF/CNPJ</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Dados do Remetende CPF/CNPJ")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpRemetente", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpRemetente
    {
        
        /// <summary>
        /// <para>Informe o CPF/CNPJ do Remetente autorizado a transmitir a mensagem XML.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o CPF/CNPJ do Remetente autorizado a transmitir a mensagem XML.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CPFCNPJ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpCpfcnpj Cpfcnpj { get; set; }
    }
    
    /// <summary>
    /// <para>Tipo que representa um CPF/CNPJ.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Tipo que representa um CPF/CNPJ.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpCPFCNPJ", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpCpfcnpj
    {
        
        /// <summary>
        /// <para>Tipo CPF.</para>
        /// <para xml:lang="en">Pattern: [0-9]{11}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{11}")]
        [System.Xml.Serialization.XmlElementAttribute("CPF", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cpf { get; set; }
        
        /// <summary>
        /// <para>Tipo CNPJ.</para>
        /// <para xml:lang="en">Pattern: [0-9]{14}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{14}")]
        [System.Xml.Serialization.XmlElementAttribute("CNPJ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cnpj { get; set; }
    }
    
    /// <summary>
    /// <para>Cabeçalho do retorno.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Cabeçalho do retorno.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpCabecalho", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpCabecalho
    {
        
        /// <summary>
        /// <para>Campo indicativo do sucesso do pedido do serviço.</para>
        /// <para>Tipo que indica se o pedido do serviço obteve sucesso.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Campo indicativo do sucesso do pedido do serviço.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Sucesso", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Sucesso { get; set; }
        
        /// <summary>
        /// <para>Informações sobre o lote processado.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informações sobre o lote processado.")]
        [System.Xml.Serialization.XmlElementAttribute("InformacoesLoteNFTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpInformacoesLoteNfts InformacoesLoteNfts { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private long _versao = 1;
        
        /// <summary>
        /// <para>Informe a Versão do Schema XML utilizado.</para>
        /// <para>Tipo Versão do Schema.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,3}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe a Versão do Schema XML utilizado.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,3}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Versao")]
        public long Versao
        {
            get
            {
                return _versao;
            }
            set
            {
                _versao = value;
            }
        }
    }
    
    /// <summary>
    /// <para>Cabeçalho do retorno para consultas.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Cabeçalho do retorno para consultas.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpCabecalhoRetorno", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpCabecalhoRetorno
    {
        
        /// <summary>
        /// <para>Campo indicativo do sucesso do pedido do serviço.</para>
        /// <para>Tipo que indica se o pedido do serviço obteve sucesso.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Campo indicativo do sucesso do pedido do serviço.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Sucesso", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Sucesso { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private long _versao = 1;
        
        /// <summary>
        /// <para>Informe a Versão do Schema XML utilizado.</para>
        /// <para>Tipo Versão do Schema.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,3}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe a Versão do Schema XML utilizado.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,3}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Versao")]
        public long Versao
        {
            get
            {
                return _versao;
            }
            set
            {
                _versao = value;
            }
        }
    }
    
    /// <summary>
    /// <para>Lista de mensagens de retorno do lote</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Lista de mensagens de retorno do lote")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpListaRetornoLote", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpListaRetornoLote
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TpEvento> _alerta;
        
        /// <summary>
        /// <para>Elemento que representa a ocorrência de eventos de alerta durante o processamento da mensagem XML.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Elemento que representa a ocorrência de eventos de alerta durante o processamento" +
            " da mensagem XML."))]
        [System.Xml.Serialization.XmlElementAttribute("Alerta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<TpEvento> Alerta
        {
            get
            {
                return _alerta;
            }
            private set
            {
                _alerta = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Alerta collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlertaSpecified
        {
            get
            {
                return (this.Alerta.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TpListaRetornoLote" /> class.</para>
        /// </summary>
        public TpListaRetornoLote()
        {
            this._alerta = new System.Collections.ObjectModel.Collection<TpEvento>();
            this._erro = new System.Collections.ObjectModel.Collection<TpEvento>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TpEvento> _erro;
        
        /// <summary>
        /// <para>Elemento que representa a ocorrência de eventos de erro durante o processamento da mensagem XML.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Elemento que representa a ocorrência de eventos de erro durante o processamento d" +
            "a mensagem XML."))]
        [System.Xml.Serialization.XmlElementAttribute("Erro", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<TpEvento> Erro
        {
            get
            {
                return _erro;
            }
            private set
            {
                _erro = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Erro collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErroSpecified
        {
            get
            {
                return (this.Erro.Count != 0);
            }
        }
    }
    
    /// <summary>
    /// <para>Lista de mensagens de retorno da NFTS</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Lista de mensagens de retorno da NFTS")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpListaRetornoNFTS", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpListaRetornoNfts
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TpEvento> _alerta;
        
        /// <summary>
        /// <para>Elemento que representa a ocorrência de eventos de alerta durante o processamento da mensagem XML.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Elemento que representa a ocorrência de eventos de alerta durante o processamento" +
            " da mensagem XML."))]
        [System.Xml.Serialization.XmlElementAttribute("Alerta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<TpEvento> Alerta
        {
            get
            {
                return _alerta;
            }
            private set
            {
                _alerta = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Alerta collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlertaSpecified
        {
            get
            {
                return (this.Alerta.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TpListaRetornoNfts" /> class.</para>
        /// </summary>
        public TpListaRetornoNfts()
        {
            this._alerta = new System.Collections.ObjectModel.Collection<TpEvento>();
            this._erro = new System.Collections.ObjectModel.Collection<TpEvento>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TpEvento> _erro;
        
        /// <summary>
        /// <para>Elemento que representa a ocorrência de eventos de erro durante o processamento da mensagem XML.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Elemento que representa a ocorrência de eventos de erro durante o processamento d" +
            "a mensagem XML."))]
        [System.Xml.Serialization.XmlElementAttribute("Erro", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<TpEvento> Erro
        {
            get
            {
                return _erro;
            }
            private set
            {
                _erro = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Erro collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErroSpecified
        {
            get
            {
                return (this.Erro.Count != 0);
            }
        }
    }
    
    /// <summary>
    /// <para>Lista de mensagens de retorno do lote</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Lista de mensagens de retorno do lote")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpListaRetornoConsultaNFTS", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpListaRetornoConsultaNfts
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TpListaRetornoLote> _listaRetornoLote;
        
        /// <summary>
        /// <para>Elemento que representa a ocorrência de eventos de erro/alerta durante o processamento da mensagem XML.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Elemento que representa a ocorrência de eventos de erro/alerta durante o processa" +
            "mento da mensagem XML."))]
        [System.Xml.Serialization.XmlElementAttribute("ListaRetornoLote", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<TpListaRetornoLote> ListaRetornoLote
        {
            get
            {
                return _listaRetornoLote;
            }
            private set
            {
                _listaRetornoLote = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ListaRetornoLote collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListaRetornoLoteSpecified
        {
            get
            {
                return (this.ListaRetornoLote.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TpListaRetornoConsultaNfts" /> class.</para>
        /// </summary>
        public TpListaRetornoConsultaNfts()
        {
            this._listaRetornoLote = new System.Collections.ObjectModel.Collection<TpListaRetornoLote>();
            this._nfts = new System.Collections.ObjectModel.Collection<TpNftsRetorno>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TpNftsRetorno> _nfts;
        
        /// <summary>
        /// <para>Elemento que representa a lista de NFTS.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Elemento que representa a lista de NFTS.")]
        [System.Xml.Serialization.XmlElementAttribute("NFTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<TpNftsRetorno> Nfts
        {
            get
            {
                return _nfts;
            }
            private set
            {
                _nfts = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Nfts collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NftsSpecified
        {
            get
            {
                return (this.Nfts.Count != 0);
            }
        }
    }
    
    /// <summary>
    /// <para>Tipo que representa uma NFTS de retorno.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Tipo que representa uma NFTS de retorno.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpNFTSRetorno", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpNftsRetorno
    {
        
        /// <summary>
        /// <para>Informe o tipo do documento NFTS</para>
        /// <para>01 - Dispensado de emissão de documento fiscal.</para>
        /// <para>02 - Com emissão de documento fiscal autorizado pelo município.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Informe o tipo do documento NFTS 01 - Dispensado de emissão de documento fiscal. " +
            "02 - Com emissão de documento fiscal autorizado pelo município."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("TipoDocumento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpTipoDocumentoNfts TipoDocumento { get; set; }
        
        /// <summary>
        /// <para>Dados do documento. Inscrição Municipal/Série/NumroDocumento.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Dados do documento. Inscrição Municipal/Série/NumroDocumento.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ChaveDocumento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpChaveDocumento ChaveDocumento { get; set; }
        
        /// <summary>
        /// <para>Código de verificação da NFTS.</para>
        /// <para>Tipo Código de verificação da NFTS.</para>
        /// <para xml:lang="en">Minimum length: 8.</para>
        /// <para xml:lang="en">Maximum length: 8.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código de verificação da NFTS.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(8)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(8)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("CodigoVerificacao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoVerificacao { get; set; }
        
        /// <summary>
        /// <para>Informe a data da prestação de serviços (Formato: AAAAMMDD).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe a data da prestação de serviços (Formato: AAAAMMDD).")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DataPrestacao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DataPrestacao { get; set; }
        
        /// <summary>
        /// <para>Informe o Status da NFTS.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o Status da NFTS.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("StatusNFTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpStatusNfts StatusNfts { get; set; }
        
        /// <summary>
        /// <para>Informe o tipo de tributação da NFTS.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o tipo de tributação da NFTS.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("TributacaoNFTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpTributacaoNfts TributacaoNfts { get; set; }
        
        /// <summary>
        /// <para>Informe o valor dos serviços.</para>
        /// <para>Tipo utilizado para valores com 15 dígitos, sendo 13 de corpo e 2 decimais.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{0,2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o valor dos serviços.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{0,2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ValorServicos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValorServicos { get; set; }
        
        /// <summary>
        /// <para>Informe o valor das deduções.</para>
        /// <para>Tipo utilizado para valores com 15 dígitos, sendo 13 de corpo e 2 decimais.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{0,2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o valor das deduções.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{0,2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ValorDeducoes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValorDeducoes { get; set; }
        
        /// <summary>
        /// <para>Informe o código do serviço da NFTS. Este código deve pertencer à lista de serviços.</para>
        /// <para>Tipo código de serviço.</para>
        /// <para xml:lang="en">Pattern: [0-9]{4,5}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Informe o código do serviço da NFTS. Este código deve pertencer à lista de serviç" +
            "os."))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{4,5}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CodigoServico", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CodigoServico { get; set; }
        
        /// <summary>
        /// <para>Informe o código do Subitem da lista de serviços.</para>
        /// <para>Código do Subitem da lista de serviços.</para>
        /// <para xml:lang="en">Pattern: [0-9]{3,4}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o código do Subitem da lista de serviços.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{3,4}")]
        [System.Xml.Serialization.XmlElementAttribute("CodigoSubItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short CodigoSubItem { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CodigoSubItem property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSubItemSpecified { get; set; }
        
        /// <summary>
        /// <para>Informe o valor da alíquota.</para>
        /// <para>Tipo utilizado para valor de alíquota</para>
        /// <para xml:lang="en">Total number of digits: 5.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 4.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o valor da alíquota.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("AliquotaServicos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal AliquotaServicos { get; set; }
        
        /// <summary>
        /// <para>Informe true para retenção do tomador ou false para sem retenção.</para>
        /// <para>Informe a retenção.</para>
        /// <para>true - ISS Retido pelo tomador.</para>
        /// <para>false - NFTS sem ISS Retido.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe true para retenção do tomador ou false para sem retenção.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ISSRetidoTomador", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IssRetidoTomador { get; set; }
        
        /// <summary>
        /// <para>Informe true para retenção de intermediário ou false para sem retenção.</para>
        /// <para>Informe a retenção.</para>
        /// <para>true - ISS Retido pelo intermediário.</para>
        /// <para>false - NFTS sem ISS Retido.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe true para retenção de intermediário ou false para sem retenção.")]
        [System.Xml.Serialization.XmlElementAttribute("ISSRetidoIntermediario", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IssRetidoIntermediario { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IssRetidoIntermediario property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssRetidoIntermediarioSpecified { get; set; }
        
        /// <summary>
        /// <para>Informe o e-mail do prestador.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o e-mail do prestador.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Prestador", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpPrestador Prestador { get; set; }
        
        /// <summary>
        /// <para>Informe o Regime de Tributação.</para>
        /// <para>Regime de Tributação.</para>
        /// <para>0 - Normal.</para>
        /// <para>4 - Simples Nacional.</para>
        /// <para>5 - Microempreendedor Individual MEI.</para>
        /// <para xml:lang="en">Pattern: 0|4|5.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o Regime de Tributação.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|4|5")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("RegimeTributacao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short RegimeTributacao { get; set; }
        
        /// <summary>
        /// <para>Informe a data em que o serviço foi pago ao prestador.</para>
        /// <para>Esta informação somente será considerada para tomadores de serviço de Orgãos Públicos.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Informe a data em que o serviço foi pago ao prestador. Esta informação somente se" +
            "rá considerada para tomadores de serviço de Orgãos Públicos."))]
        [System.Xml.Serialization.XmlElementAttribute("DataPagamento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DataPagamento { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the DataPagamento property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataPagamentoSpecified { get; set; }
        
        /// <summary>
        /// <para>Informe a discriminação dos serviços.</para>
        /// <para>Tipo Discriminação Serviços.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe a discriminação dos serviços.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2000)]
        [System.Xml.Serialization.XmlElementAttribute("Discriminacao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Discriminacao { get; set; }
        
        /// <summary>
        /// <para>Dados do tomador de serviço.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Dados do tomador de serviço.")]
        [System.Xml.Serialization.XmlElementAttribute("Tomador", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpTomador Tomador { get; set; }
        
        /// <summary>
        /// <para>Informe o Código CEI.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("CodigoCEI", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{12}")]
        public string CodigoCEI { get; set; }

        /// <summary>
        /// <para>Informe a Matrícula da Obra.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("MatriculaObra", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{12}")]
        public string MatriculaObra { get; set; }

        /// <summary>
        /// <para>Informe o código do local de prestação de serviço.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("clocalPrestServ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{7}")]
        public string ClocalPrestServ { get; set; }

        /// <summary>
        /// <para>Informe o código do país de prestação de serviço.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("cPaisPrestServ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.StringLength(2, MinimumLength = 2)]
        public string CPaisPrestServ { get; set; }

        /// <summary>
        /// <para>Informe o valor do PIS.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorPIS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorPIS { get; set; }

        /// <summary>
        /// <para>Informe o valor do COFINS.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorCOFINS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorCOFINS { get; set; }

        /// <summary>
        /// <para>Informe o valor do INSS.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorINSS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorINSS { get; set; }

        /// <summary>
        /// <para>Informe o valor do IR.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorIR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorIR { get; set; }

        /// <summary>
        /// <para>Informe o valor do CSLL.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorCSLL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorCSLL { get; set; }

        /// <summary>
        /// <para>Informe o valor do IPI.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorIPI", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorIPI { get; set; }

        /// <summary>
        /// <para>Informe o retorno complementar IBS CBS.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("RetornoComplementarIBSCBS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int RetornoComplementarIBSCBS { get; set; }

        /// <summary>
        /// <para>Informe o valor inicial cobrado.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorInicialCobrado", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorInicialCobrado { get; set; }

        /// <summary>
        /// <para>Informe o valor final cobrado.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorFinalCobrado", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorFinalCobrado { get; set; }

        /// <summary>
        /// <para>Informe o valor da multa.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorMulta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorMulta { get; set; }

        /// <summary>
        /// <para>Informe o valor dos juros.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorJuros", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorJuros { get; set; }

        /// <summary>
        /// <para>Informe se há exigibilidade suspensa.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ExigibilidadeSuspensa", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ExigibilidadeSuspensa { get; set; }

        /// <summary>
        /// <para>Informe se há pagamento parcelado antecipado.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PagamentoParceladoAntecipado", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int PagamentoParceladoAntecipado { get; set; }
    }
    
    /// <summary>
    /// <para>Dados do Prestador de serviço</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Dados do Prestador de serviço")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpPrestador", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpPrestador
    {
        
        /// <summary>
        /// <para>Informe o CPF/CNPJ do prestador do serviço.</para>
        /// <para>Para prestador de serviço estrangeiro, não enviara esta TAG</para>
        /// <para>Caso o campo ISS Retido esteja preenchido com 3, o preenchimento deste campo é com zeros</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Informe o CPF/CNPJ do prestador do serviço. Para prestador de serviço estrangeiro" +
            ", não enviara esta TAG Caso o campo ISS Retido esteja preenchido com 3, o preenc" +
            "himento deste campo é com zeros"))]
        [System.Xml.Serialization.XmlElementAttribute("CPFCNPJ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpCpfcnpj Cpfcnpj { get; set; }
        
        /// <summary>
        /// <para>Informe a Inscrição Municipal do Prestador.</para>
        /// <para>ATENÇÃO: Este campo só deverá ser preenchido para prestadores estabelecidos no município de São Paulo (CCM).</para>
        /// <para>Quando este campo for preenchido, seu conteúdo será considerado como prioritário com relação ao campo de CPF/CNPJ do Prestador, sendo utilizado para identificar o Prestador e recuperar seus dados da base de dados da Prefeitura.</para>
        /// <para>Tipo padrão referente a inscrição municipal.</para>
        /// <para xml:lang="en">Pattern: [0-9]{8,8}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Informe a Inscrição Municipal do Prestador. ATENÇÃO: Este campo só deverá ser preenchido para prestadores estabelecidos no município de São Paulo (CCM). Quando este campo for preenchido, seu conteúdo será considerado como prioritário com relação ao campo de CPF/CNPJ do Prestador, sendo utilizado para identificar o Prestador e recuperar seus dados da base de dados da Prefeitura.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{8,8}")]
        [System.Xml.Serialization.XmlElementAttribute("InscricaoMunicipal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long InscricaoMunicipal { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the InscricaoMunicipal property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InscricaoMunicipalSpecified { get; set; }
        
        /// <summary>
        /// <para>Informe o Nome/Razão Social do Prestador.</para>
        /// <para>Este campo será ignorado caso seja fornecido um CPF/CNPJ ou a Inscrição Municipal do prestador pertença a São Paulo.</para>
        /// <para>Tipo Razão Social.</para>
        /// <para xml:lang="en">Maximum length: 75.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Informe o Nome/Razão Social do Prestador. Este campo será ignorado caso seja forn" +
            "ecido um CPF/CNPJ ou a Inscrição Municipal do prestador pertença a São Paulo."))]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(75)]
        [System.Xml.Serialization.XmlElementAttribute("RazaoSocialPrestador", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RazaoSocialPrestador { get; set; }
        
        /// <summary>
        /// <para>Informe o endereço do prestador.</para>
        /// <para>O conteúdo destes campos será ignorado caso seja fornecido um CNPJ/CPF ou a Inscrição Municipal do prestador pertença ao município de São Paulo.</para>
        /// <para>Se estes campos estiverem informados, serão considerados no caso de prestador sem Inscrição Municipal. Nesta situação os dados da Receita Federal não serão considerados.</para>
        /// <para>Os dados da Receita Federal serão utilizados apenas se estes dados não estiverem informados.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Informe o endereço do prestador. O conteúdo destes campos será ignorado caso seja fornecido um CNPJ/CPF ou a Inscrição Municipal do prestador pertença ao município de São Paulo. Se estes campos estiverem informados, serão considerados no caso de prestador sem Inscrição Municipal. Nesta situação os dados da Receita Federal não serão considerados. Os dados da Receita Federal serão utilizados apenas se estes dados não estiverem informados.")]
        [System.Xml.Serialization.XmlElementAttribute("Endereco", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpEndereco Endereco { get; set; }
        
        /// <summary>
        /// <para>Informe o e-mail do prestador.</para>
        /// <para>Tipo E-mail.</para>
        /// <para xml:lang="en">Maximum length: 75.</para>
        /// <para xml:lang="en">Pattern: ^[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*\.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*$.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o e-mail do prestador.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(75)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute(("^[A-Za-z0-9_]+([-+.\'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*\\.[A-Za-z0-" +
            "9_]+([-.][A-Za-z0-9_]+)*$"))]
        [System.Xml.Serialization.XmlElementAttribute("Email", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Email { get; set; }
    }
    
    /// <summary>
    /// <para>Tipo Endereço.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Tipo Endereço.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpEndereco", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpEndereco
    {
        
        /// <summary>
        /// <para>Tipo do endereço (Rua, Av, ...).</para>
        /// <para xml:lang="en">Maximum length: 3.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(3)]
        [System.Xml.Serialization.XmlElementAttribute("TipoLogradouro", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TipoLogradouro { get; set; }
        
        /// <summary>
        /// <para>Endereço.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlElementAttribute("Logradouro", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Logradouro { get; set; }
        
        /// <summary>
        /// <para>Tipo número do endereço.</para>
        /// <para xml:lang="en">Maximum length: 10.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(10)]
        [System.Xml.Serialization.XmlElementAttribute("NumeroEndereco", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NumeroEndereco { get; set; }
        
        /// <summary>
        /// <para>Tipo complemento do endereço.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.Xml.Serialization.XmlElementAttribute("ComplementoEndereco", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ComplementoEndereco { get; set; }
        
        /// <summary>
        /// <para>Tipo bairro.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.Xml.Serialization.XmlElementAttribute("Bairro", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bairro { get; set; }
        
        /// <summary>
        /// <para>Tipo cidade em formato texto.</para>
        /// <para xml:lang="en">Minimum length: 3.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(3)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlElementAttribute("Cidade", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cidade { get; set; }
        
        /// <summary>
        /// <para>Tipo UF.</para>
        /// <para xml:lang="en">Minimum length: 2.</para>
        /// <para xml:lang="en">Maximum length: 2.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(2)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2)]
        [System.Xml.Serialization.XmlElementAttribute("UF", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Uf { get; set; }
        
        /// <summary>
        /// <para>Tipo CEP.</para>
        /// <para xml:lang="en">Pattern: [0-9]{7,8}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{7,8}")]
        [System.Xml.Serialization.XmlElementAttribute("CEP", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Cep { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Cep property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CepSpecified { get; set; }
    }
    
    /// <summary>
    /// <para>Dados do tomador de serviço</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Dados do tomador de serviço")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpTomador", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpTomador
    {
        
        /// <summary>
        /// <para>CPF/CNPJ do tomador de serviço.</para>
        /// <para>Para os casos em que a NFTS se tratar de nota fiscal do intermediário, obrigatório informar o CPF/CNPJ do tomador.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("CPF/CNPJ do tomador de serviço. Para os casos em que a NFTS se tratar de nota fis" +
            "cal do intermediário, obrigatório informar o CPF/CNPJ do tomador."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CPFCNPJ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpCpfcnpj Cpfcnpj { get; set; }
        
        /// <summary>
        /// <para>Informe o Nome/Razão Social do Tomador.</para>
        /// <para>Para os casos em que a NFTS se tratar de nota fiscal do intermediário, obrigatório informar a Razão Social do tomador.</para>
        /// <para>Tipo Razão Social.</para>
        /// <para xml:lang="en">Maximum length: 75.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Informe o Nome/Razão Social do Tomador. Para os casos em que a NFTS se tratar de " +
            "nota fiscal do intermediário, obrigatório informar a Razão Social do tomador."))]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(75)]
        [System.Xml.Serialization.XmlElementAttribute("RazaoSocial", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RazaoSocial { get; set; }
    }
    
    /// <summary>
    /// <para>Dados do Remetende CPF/CNPJ e Inscricao Municipal</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Dados do Remetende CPF/CNPJ e Inscricao Municipal")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpRemetente_ComCCM", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpRemetenteComCcm
    {
        
        /// <summary>
        /// <para>Informe o CPF/CNPJ do Remetente autorizado a transmitir a mensagem XML de cancelamento de NFTS.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Informe o CPF/CNPJ do Remetente autorizado a transmitir a mensagem XML de cancela" +
            "mento de NFTS."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CPFCNPJ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpCpfcnpj Cpfcnpj { get; set; }
        
        /// <summary>
        /// <para>Informe a Inscrição Municipal do Remetente autorizado a transmitir a mensagem XML de cancelamento de NFTS.</para>
        /// <para>Tipo padrão referente a inscrição municipal.</para>
        /// <para xml:lang="en">Pattern: [0-9]{8,8}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Informe a Inscrição Municipal do Remetente autorizado a transmitir a mensagem XML" +
            " de cancelamento de NFTS."))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{8,8}")]
        [System.Xml.Serialization.XmlElementAttribute("InscricaoMunicipal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long InscricaoMunicipal { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the InscricaoMunicipal property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InscricaoMunicipalSpecified { get; set; }
    }
    
    /// <summary>
    /// <para>Tipo que representa uma NFTS.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Tipo que representa uma NFTS.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tpNFTS", Namespace="http://www.prefeitura.sp.gov.br/nfts/tipos")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TpNfts
    {
        
        /// <summary>
        /// <para>Informe o tipo do documento NFTS</para>
        /// <para>01 - Dispensado de emissão de documento fiscal.</para>
        /// <para>02 - Com emissão de documento fiscal autorizado pelo município.</para>
        /// <para>03 - Sem emissão de documento fiscal embora obrigado</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Informe o tipo do documento NFTS 01 - Dispensado de emissão de documento fiscal. " +
            "02 - Com emissão de documento fiscal autorizado pelo município. 03 - Sem emissão" +
            " de documento fiscal embora obrigado"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("TipoDocumento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpTipoDocumentoNfts TipoDocumento { get; set; }
        
        /// <summary>
        /// <para>Informe a série da NFTS.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe a série da NFTS.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ChaveDocumento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpChaveDocumento ChaveDocumento { get; set; }
        
        /// <summary>
        /// <para>Informe a data da prestação de serviços (Formato: AAAAMMDD).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe a data da prestação de serviços (Formato: AAAAMMDD).")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DataPrestacao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DataPrestacao { get; set; }
        
        /// <summary>
        /// <para>Informe o Status da NFTS.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o Status da NFTS.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("StatusNFTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpStatusNfts StatusNfts { get; set; }
        
        /// <summary>
        /// <para>Informe o tipo de tributação da NFTS.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o tipo de tributação da NFTS.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("TributacaoNFTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpTributacaoNfts TributacaoNfts { get; set; }
        
        /// <summary>
        /// <para>Informe o valor dos serviços.</para>
        /// <para>Tipo utilizado para valores com 15 dígitos, sendo 13 de corpo e 2 decimais.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{0,2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o valor dos serviços.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{0,2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ValorServicos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValorServicos { get; set; }
        
        /// <summary>
        /// <para>Informe o valor das deduções.</para>
        /// <para>Tipo utilizado para valores com 15 dígitos, sendo 13 de corpo e 2 decimais.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{0,2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o valor das deduções.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{0,2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ValorDeducoes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValorDeducoes { get; set; }
        
        /// <summary>
        /// <para>Informe o código do serviço da NFTS. Este código deve pertencer à lista de serviços.</para>
        /// <para>Tipo código de serviço.</para>
        /// <para xml:lang="en">Pattern: [0-9]{4,5}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Informe o código do serviço da NFTS. Este código deve pertencer à lista de serviç" +
            "os."))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{4,5}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CodigoServico", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CodigoServico { get; set; }
        
        /// <summary>
        /// <para>Informe o código do Subitem da lista de serviços.</para>
        /// <para>Código do Subitem da lista de serviços.</para>
        /// <para xml:lang="en">Pattern: [0-9]{3,4}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o código do Subitem da lista de serviços.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{3,4}")]
        [System.Xml.Serialization.XmlElementAttribute("CodigoSubItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short CodigoSubItem { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CodigoSubItem property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSubItemSpecified { get; set; }
        
        /// <summary>
        /// <para>Informe o valor da alíquota.</para>
        /// <para>Tipo utilizado para valor de alíquota</para>
        /// <para xml:lang="en">Total number of digits: 5.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 4.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o valor da alíquota.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("AliquotaServicos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal AliquotaServicos { get; set; }
        
        /// <summary>
        /// <para>Informe true para retenção do tomador ou false para sem retenção.</para>
        /// <para>Informe a retenção.</para>
        /// <para>true - ISS Retido pelo tomador.</para>
        /// <para>false - NFTS sem ISS Retido.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe true para retenção do tomador ou false para sem retenção.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ISSRetidoTomador", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IssRetidoTomador { get; set; }
        
        /// <summary>
        /// <para>Informe true para retenção de intermediário ou false para sem retenção.</para>
        /// <para>Informe a retenção.</para>
        /// <para>true - ISS Retido pelo intermediário.</para>
        /// <para>false - NFTS sem ISS Retido.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe true para retenção de intermediário ou false para sem retenção.")]
        [System.Xml.Serialization.XmlElementAttribute("ISSRetidoIntermediario", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IssRetidoIntermediario { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IssRetidoIntermediario property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssRetidoIntermediarioSpecified { get; set; }
        
        /// <summary>
        /// <para>Informe o e-mail do prestador.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o e-mail do prestador.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Prestador", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpPrestador Prestador { get; set; }
        
        /// <summary>
        /// <para>Informe o Regime de Tributação.</para>
        /// <para>Regime de Tributação.</para>
        /// <para>0 - Normal.</para>
        /// <para>4 - Simples Nacional.</para>
        /// <para>5 - Microempreendedor Individual MEI.</para>
        /// <para xml:lang="en">Pattern: 0|4|5.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe o Regime de Tributação.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|4|5")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("RegimeTributacao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short RegimeTributacao { get; set; }
        
        /// <summary>
        /// <para>Informe a data em que o serviço foi pago ao prestador.</para>
        /// <para>Esta informação somente será considerada para tomadores de serviço de Orgãos Públicos.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Informe a data em que o serviço foi pago ao prestador. Esta informação somente se" +
            "rá considerada para tomadores de serviço de Orgãos Públicos."))]
        [System.Xml.Serialization.XmlElementAttribute("DataPagamento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DataPagamento { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the DataPagamento property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataPagamentoSpecified { get; set; }
        
        /// <summary>
        /// <para>Informe a discriminação dos serviços.</para>
        /// <para>Tipo Discriminação Serviços.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informe a discriminação dos serviços.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2000)]
        [System.Xml.Serialization.XmlElementAttribute("Discriminacao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Discriminacao { get; set; }
        
        /// <summary>
        /// <para>Define se a NFTS é do tomador ou intermediário.</para>
        /// <para>Tipo da NFTS.</para>
        /// <para>1 - Nota Fiscal do Tomador.</para>
        /// <para>2 - Nota Fiscal do Intermediário.</para>
        /// <para xml:lang="en">Pattern: 1|2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Define se a NFTS é do tomador ou intermediário.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("1|2")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("TipoNFTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short TipoNfts { get; set; }
        
        /// <summary>
        /// <para>Dados do tomador de serviço.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Dados do tomador de serviço.")]
        [System.Xml.Serialization.XmlElementAttribute("Tomador", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TpTomador Tomador { get; set; }

   /*
        /// <summary>
        /// <para>Informe o Código CEI.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("CodigoCEI", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{12}")]
        public string CodigoCEI { get; set; }

        /// <summary>
        /// <para>Informe a Matrícula da Obra.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("MatriculaObra", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{12}")]
        public string MatriculaObra { get; set; }

        /// <summary>
        /// <para>Informe o código do local de prestação de serviço.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("clocalPrestServ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{7}")]
        public string ClocalPrestServ { get; set; }

        /// <summary>
        /// <para>Informe o código do país de prestação de serviço.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("cPaisPrestServ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.StringLength(2, MinimumLength = 2)]
        public string CPaisPrestServ { get; set; }

        /// <summary>
        /// <para>Informe o valor do PIS.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorPIS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorPIS { get; set; }

        /// <summary>
        /// <para>Informe o valor do COFINS.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorCOFINS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorCOFINS { get; set; }

        /// <summary>
        /// <para>Informe o valor do INSS.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorINSS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorINSS { get; set; }

        /// <summary>
        /// <para>Informe o valor do IR.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorIR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorIR { get; set; }

        /// <summary>
        /// <para>Informe o valor do CSLL.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorCSLL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorCSLL { get; set; }

        /// <summary>
        /// <para>Informe o valor do IPI.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorIPI", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorIPI { get; set; }

        /// <summary>
        /// <para>Informe o retorno complementar IBS CBS.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("RetornoComplementarIBSCBS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int RetornoComplementarIBSCBS { get; set; }

        /// <summary>
        /// <para>Informe o valor inicial cobrado.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorInicialCobrado", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorInicialCobrado { get; set; }

        /// <summary>
        /// <para>Informe o valor final cobrado.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorFinalCobrado", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorFinalCobrado { get; set; }

        /// <summary>
        /// <para>Informe o valor da multa.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorMulta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorMulta { get; set; }

        /// <summary>
        /// <para>Informe o valor dos juros.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ValorJuros", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DataAnnotations.Range(0, double.MaxValue)]
        public decimal ValorJuros { get; set; }
*/

        /// <summary>
        /// <para>Informe se há exigibilidade suspensa.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public int ExigibilidadeSuspensa { get; set; }

        /// <summary>
        /// <para>Informe se há pagamento parcelado antecipado.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public int PagamentoParceladoAntecipado { get; set; }        
        
        /// <summary>
        /// <para>Assinatura digital da NFTS.</para>
        /// <para>Assinatura digital do RPS emitido.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Assinatura digital da NFTS.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Assinatura", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] Assinatura { get; set; }
    }
    
    /// <summary>
    /// <para>Schema utilizado para Retorno de envio de lote de NFTS.</para>
    /// <para>Este Schema XML é utilizado para informar os tomadores/intermediários de serviços o resultado do pedido do envio do lote da emissão de NFTS.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Schema utilizado para Retorno de envio de lote de NFTS. Este Schema XML é utiliza" +
        "do para informar os tomadores/intermediários de serviços o resultado do pedido d" +
        "o envio do lote da emissão de NFTS."))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RetornoEnvioNFTS", Namespace="http://www.prefeitura.sp.gov.br/nfts", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("RetornoEnvioNFTS", Namespace="http://www.prefeitura.sp.gov.br/nfts")]
    public partial class RetornoEnvioNfts
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Cabecalho", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AssinadorNFTS.Models.TpCabecalhoRetorno Cabecalho { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AssinadorNFTS.Models.TpListaRetornoLote> _listaRetornoNfts;
        
        /// <summary>
        /// <para>Elemento que representa a ocorrência de eventos ou NFTS durante o processamento da mensagem XML.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Elemento que representa a ocorrência de eventos ou NFTS durante o processamento d" +
            "a mensagem XML."))]
        [System.Xml.Serialization.XmlElementAttribute("ListaRetornoNFTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<AssinadorNFTS.Models.TpListaRetornoLote> ListaRetornoNfts
        {
            get
            {
                return _listaRetornoNfts;
            }
            private set
            {
                _listaRetornoNfts = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ListaRetornoNfts collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListaRetornoNftsSpecified
        {
            get
            {
                return (this.ListaRetornoNfts.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RetornoEnvioNfts" /> class.</para>
        /// </summary>
        public RetornoEnvioNfts()
        {
            this._listaRetornoNfts = new System.Collections.ObjectModel.Collection<AssinadorNFTS.Models.TpListaRetornoLote>();
        }
        
        /// <summary>
        /// <para>Identificação da NFTS gerada.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identificação da NFTS gerada.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ChaveNFTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AssinadorNFTS.Models.TpChaveNfts ChaveNfts { get; set; }
    }
}
